project:
  type: book
  render:
    - "*.qmd"

book:
  title: "CRRESS Book"
  repo-url: https://github.com/labordynamicsinstitute/crress-book
  repo-actions: [edit]
  # downloads: [pdf]
  navbar:
    search: true
    pinned: true
    logo: "images/LDI Conf CRRESS V4.png"
    right:
      - text: Archive
        url: https://ecommons.cornell.edu/collections/90b9b044-4fa7-4dc2-9c84-ee9ebb8ab3d8
      - text: Learn More
        menu:
          - text: CRRESS Main
            url: https://labordynamicsinstitute.github.io/crress/
          - text: CRRESS Sessions
            url: https://labordynamicsinstitute.github.io/crress/#projects
    # background: "#f8f8f8"
  subtitle: Conference on Reproducibility and Replicability in Economics and the Social Sciences
  cover-image: "images/LDI Conf CRRESS V4.png"
  page-navigation: true
  page-footer: 
    # background: "#f8f8f8"
    left: "Copyright 2022, Cornell University or with the authors"
    right:
      - icon: home
        href: https://labordynamicsinstitute.github.io/crress/
  reader-mode: true
  search: true
  chapters:
    - index.qmd
    - about.qmd
    - part: sessions/1/session1_intro.qmd
      chapters:
        - sessions/1/salmon/index.qmd
        - sessions/1/whited/index.qmd
    - part: sessions/2/session2_intro.qmd
      chapters:
        - sessions/2/swauger/index.qmd
    - part: sessions/3/session3_intro.qmd
      chapters:
        - sessions/3/diego/index.qmd
        - sessions/3/ball/index.qmd
    - part: sessions/4/session4_intro.qmd
      chapters:
        - sessions/4/guimaraes/index.qmd
    - part: sessions/5/session5_intro.qmd
      chapters:
        - sessions/5/hoynes/index.qmd
        - sessions/5/weeden/index.qmd
    - part: sessions/6/session6_intro.qmd
      chapters:
        - sessions/6/perignon/index.qmd
    - part: sessions/7/session7_intro.qmd
      chapters:
        - sessions/7/macdonald/index.qmd
        - sessions/7/butler/index.qmd
        - sessions/7/peer/index.qmd
    - part: sessions/8/session8_intro.qmd
      chapters:
        - sessions/8/buck/index.qmd
    - part: sessions/9/session9_intro.qmd
      chapters:
        - sessions/9/mcgrail/index.qmd
        - sessions/9/taylor/index.qmd
format:
  html:
    theme: 
      light: minty
      dark: darkly
    # css: styles.css
    toc: true
    number-sections: false
  pdf:
    documentclass: scrreport
execute:
  freeze: auto


